// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbKGRSst34YB9VjSfnTpnuyh7EPtQhCHU',
    appId: '1:500771382613:web:3ab957c47ec47077e5fbdc',
    messagingSenderId: '500771382613',
    projectId: 'my-last-and-final-project',
    authDomain: 'my-last-and-final-project.firebaseapp.com',
    storageBucket: 'my-last-and-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwjRPSC-et8PXYKwS3YglcsWjFJrG7a1A',
    appId: '1:500771382613:android:249c970fad225ce4e5fbdc',
    messagingSenderId: '500771382613',
    projectId: 'my-last-and-final-project',
    storageBucket: 'my-last-and-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4gpibut8-dsP98I4kCBX4BMKIj9HPnQ',
    appId: '1:500771382613:ios:2528962fb5507f2ee5fbdc',
    messagingSenderId: '500771382613',
    projectId: 'my-last-and-final-project',
    storageBucket: 'my-last-and-final-project.appspot.com',
    iosBundleId: 'com.example.kwikqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4gpibut8-dsP98I4kCBX4BMKIj9HPnQ',
    appId: '1:500771382613:ios:c90cd673b99ac54fe5fbdc',
    messagingSenderId: '500771382613',
    projectId: 'my-last-and-final-project',
    storageBucket: 'my-last-and-final-project.appspot.com',
    iosBundleId: 'com.example.kwikqApp.RunnerTests',
  );
}
